[package]
name = "coins-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.36.0", features = ["bundled"] }
rusqlite_migration = { version = "2.2.0", features = ["from-directory"] }
